//Generated by a python script.

Multivio.CDMFixtures = {
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711001_001_06.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1858079, 
    "mime": "application/pdf", 
    "nPages": 6, 
    "title": "18711001_001_06.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711004_003_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1170115, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711004_003_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711005_004_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1163169, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711005_004_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711006_005_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1168978, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711006_005_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711007_006_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1194063, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711007_006_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711008_007_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1146872, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711008_007_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711010_008_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1175911, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711010_008_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711011_009_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1253109, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711011_009_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711012_010_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1221866, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711012_010_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711013_011_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1223135, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711013_011_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711014_012_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1234531, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711014_012_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711015_013_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1215186, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711015_013_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711017_014_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1239439, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711017_014_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711018_015_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1247240, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711018_015_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711019_016_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1201819, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711019_016_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711020_017_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1183216, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711020_017_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711021_018_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1180755, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711021_018_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711022_019_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1160084, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711022_019_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711024_020_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1165862, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711024_020_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711025_021_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1179165, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711025_021_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711026_022_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1164619, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711026_022_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711027_023_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1162018, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711027_023_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711028_024_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1161425, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711028_024_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711029_025_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1120627, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711029_025_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711031_026_04.pdf": {
    "creator": [
      ""
    ], 
    "fileSize": 1208152, 
    "mime": "application/pdf", 
    "nPages": 4, 
    "title": "18711031_026_04.pdf"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/lm.php?url=1000,41,4,20050426144845-AC/1_mem_MoscatelliSteinerS.pdf": {
    "creator": "ethwicky", 
    "fileSize": 373048, 
    "mime": "application/pdf", 
    "nPages": 82, 
    "title": "Microsoft Word - M\u00e9moire def 4.doc"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/record/10138/export/xm": {
    "creator": [], 
    "language": "fre", 
    "mime": "text/xml", 
    "title": "La Libert\u00e9"
  }, 
  "/server/metadata/get?url=http://doc.rero.ch/record/4321/export/xm": {
    "creator": [
      "Moscatelli-Steiner, Sandra"
    ], 
    "language": "fre", 
    "mime": "text/xml", 
    "title": "\"Ho rifatto la mia vita due volte\""
  }, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711001_001_06.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711004_003_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711005_004_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711006_005_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711007_006_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711008_007_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711010_008_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711011_009_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711012_010_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711013_011_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711014_012_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711015_013_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711017_014_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711018_015_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711019_016_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711020_017_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711021_018_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711022_019_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711024_020_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711025_021_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711026_022_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711027_023_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711028_024_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711029_025_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711031_026_04.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/lm.php?url=1000,41,4,20050426144845-AC/1_mem_MoscatelliSteinerS.pdf": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/record/10138/export/xm": null, 
  "/server/structure/get_logical?url=http://doc.rero.ch/record/4321/export/xm": null, 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711001_001_06.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711001_001_06.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711001_001_06.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711004_003_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711004_003_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711004_003_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711005_004_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711005_004_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711005_004_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711006_005_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711006_005_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711006_005_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711007_006_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711007_006_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711007_006_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711008_007_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711008_007_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711008_007_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711010_008_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711010_008_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711010_008_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711011_009_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711011_009_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711011_009_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711012_010_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711012_010_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711012_010_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711013_011_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711013_011_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711013_011_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711014_012_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711014_012_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711014_012_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711015_013_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711015_013_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711015_013_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711017_014_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711017_014_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711017_014_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711018_015_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711018_015_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711018_015_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711019_016_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711019_016_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711019_016_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711020_017_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711020_017_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711020_017_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711021_018_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711021_018_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711021_018_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711022_019_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711022_019_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711022_019_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711024_020_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711024_020_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711024_020_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711025_021_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711025_021_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711025_021_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711026_022_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711026_022_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711026_022_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711027_023_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711027_023_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711027_023_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711028_024_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711028_024_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711028_024_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711029_025_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711029_025_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711029_025_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,25,1,18711031_026_04.pdf": [
    {
      "label": "lm.php?url=1000,25,1,18711031_026_04.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711031_026_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/lm.php?url=1000,41,4,20050426144845-AC/1_mem_MoscatelliSteinerS.pdf": [
    {
      "label": "1_mem_MoscatelliSteinerS.pdf", 
      "url": "http://doc.rero.ch/lm.php?url=1000,41,4,20050426144845-AC/1_mem_MoscatelliSteinerS.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/record/10138/export/xm": [
    {
      "label": "lm.php?url=1000,25,1,18711001_001_06", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711001_001_06.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711004_003_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711004_003_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711005_004_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711005_004_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711006_005_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711006_005_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711007_006_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711007_006_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711008_007_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711008_007_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711010_008_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711010_008_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711011_009_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711011_009_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711012_010_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711012_010_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711013_011_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711013_011_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711014_012_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711014_012_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711015_013_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711015_013_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711017_014_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711017_014_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711018_015_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711018_015_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711019_016_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711019_016_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711020_017_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711020_017_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711021_018_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711021_018_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711022_019_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711022_019_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711024_020_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711024_020_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711025_021_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711025_021_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711026_022_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711026_022_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711027_023_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711027_023_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711028_024_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711028_024_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711029_025_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711029_025_04.pdf"
    }, 
    {
      "label": "lm.php?url=1000,25,1,18711031_026_04", 
      "url": "http://doc.rero.ch/lm.php?url=1000,25,1,18711031_026_04.pdf"
    }
  ], 
  "/server/structure/get_physical?url=http://doc.rero.ch/record/4321/export/xm": [
    {
      "label": "Texte int\u00e9gral", 
      "url": "http://doc.rero.ch/lm.php?url=1000,41,4,20050426144845-AC/1_mem_MoscatelliSteinerS.pdf"
    }
  ], 
  "/version": {
    "api_version": "0.4.0", 
    "name": "Multivio Server", 
    "version": "0.4.0"
  }
};